### ISSUE TITLE
Implement interfaces for key/value store

### ISSUE THREAD

**Issue by drvan** [jakevoytko/crbot#6]
The redis data store (and possibly discord session) can be implemented as an interface, allowing mock dependency injections, and flexibility to use a different underlying data store at a later date.

The data store should be pretty straightforward - a preliminary look at the code seems to indicate it's primarily used as a key value store. This can probably be abstracted to simply put, get, exists (perhaps buckets are needed).

The discord interface is a little trickier - this is implemented as a event handler. Not sure what the best approach is here - reader/writer? Some other generic event handler structure?

**Comment by jakevoytko** [comment]
Key/value store is easy enough that an interface `Has()`, `Get()` and `Set()` will be good for the near future. :shipit: 

One option for Discord, is not abstracting out Discord, instead changing the `Execute` function to return a response array of 0 or more strings. The top-level handler would then speak them. Has the advantage that the function implementations would be less buggy, since you could just `return` your user-facing error messages, instead of accidentally printing them and then continuing.

Still sitting on this part; in my mind, I have until the other TODOs are addressed to do this. So I'm going to sit on it, in case I change my mind to an alternative like "Make a `Speak()` interface or function that is passed into the `Feature`s"

**Comment by drvan** [comment]
```go
type Datastore interface {
	Has(bucket string, key string) (bool, error)
	Get(bucket string, key string) (string, error)
	Set(bucket string, key string, value string) error
}

type Responder interface {
	Respond(arg string) (string, error)
}
```
Thoughts?

**Comment by jakevoytko** [comment]
Now that I've had a few days to sit on this, I'm going to do the DataStore one now, and split off a second ticket for how Discord should be abstracted out. I keep thinking of extra things that I want to implement (for instance, "unlearn shouldn't work in private channels"), so I want to sit on that one for a little while longer

**Comment by jakevoytko** [comment]
Filed https://github.com/jakevoytko/crbot/issues/8
