### ISSUE TITLE
Abstract Discord API for testing

### ISSUE THREAD

**Issue by jakevoytko** [jakevoytko/crbot#8]
Create an abstraction for DiscordGo that allows me to substitute in fakes for tests.

I have a few options: one is creating fine-grained interfaces for the different behaviors that I want to use from the API. Another is to just add interfaces that are identical to the DiscordGo API, and use my types instead of theirs.

**Comment by drvan** [comment]
Interfaces identical to DiscordGo sounds to me like a bit too much work and we'd be at the mercy of discordgo API changes, but not sure what's the best approach. I think the ideal test plan would be substituting discordgo with a reader/writer - you could do tests via stdin/stdout, or file, or anything really. However, since discordgo is event based, I can't fathom how to do this. Will need to sleep on this one.

**Comment by jakevoytko** [comment]
The interfaces only need the functions that are actually invoked, because Golang. All of the datatypes are just dumb data objects, so the actual types can be Discord types.  I just tested that it's possible to create a session interface like this:

```
type MySession interface {
	ChannelMessageSend(channel, response string) (*discordgo.Message, error)
}
```

Plus, I need to vendor all the libraries for Bazel support, which enables upgrading Discordgo and usages together, as opposed to now, where it just happens to work because Discordgo isn't upgraded that often (man, Golang is really scary when you say its default behavior out loud.)
